version: '3.8'
networks:
  shopflow-net:
    driver: bridge
volumes:
  postgres-data:
services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: shopflow
      POSTGRES_PASSWORD: secret123
      POSTGRES_DB: shopflowdb
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./scripts/init-db.sql:/docker-entrypoint-initdb.d/init.sql
    networks: [shopflow-net]
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U shopflow']
      interval: 10s
      timeout: 5s
      retries: 5

  user-service:
    build: { context: ./services/user-service, target: production }
    ports: ['3001:3001']
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: shopflowdb
      DB_USER: shopflow
      DB_PASS: secret123
      JWT_SECRET: dev-jwt-secret-change-in-prod
    depends_on: { postgres: { condition: service_healthy } }
    networks: [shopflow-net]

  product-service:
    build: { context: ./services/product-service, target: production }
    ports: ['5001:5001']
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: shopflowdb
      DB_USER: shopflow
      DB_PASS: secret123
    depends_on: { postgres: { condition: service_healthy } }
    networks: [shopflow-net]

  order-service:
    build: { context: ./services/order-service, target: production }
    ports: ['3002:3002']
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: shopflowdb
      DB_USER: shopflow
      DB_PASS: secret123
      PRODUCT_SERVICE_URL: http://product-service:5001
      USER_SERVICE_URL: http://user-service:3001
    depends_on: { postgres: { condition: service_healthy } }
    networks: [shopflow-net]

  nginx:
    image: nginx:alpine
    ports: ['80:80']
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on: [user-service, product-service, order-service]
    networks: [shopflow-net]
