apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: aws-secrets-store
  namespace: shopflow
spec:
  provider:
    aws:
      service: SecretsManager
      region: ap-south-1
      auth:
        jwt:
          serviceAccountRef:
            name: shopflow-sa
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: shopflow-db-secret
  namespace: shopflow
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-store
    kind: SecretStore
  target:
    name: db-credentials
  data:
    - secretKey: DB_PASS
      remoteRef:
        key: shopflow/db-password
