{{- if .Values.dbCredentials.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.dbCredentials.name }}
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  DB_HOST: {{ .Values.dbCredentials.data.DB_HOST | quote }}
  DB_PORT: {{ .Values.dbCredentials.data.DB_PORT | quote }}
  DB_NAME: {{ .Values.dbCredentials.data.DB_NAME | quote }}
  DB_USER: {{ .Values.dbCredentials.data.DB_USER | quote }}
  DB_PASSWORD: {{ .Values.dbCredentials.data.DB_PASSWORD | quote }}
{{- end }}